### ISSUE TITLE
Adding new FSR, CAS, Nvidia scaling results

### ISSUE THREAD

**Issue by CrHasher** [Artoriuz/artoriuz.github.io#12]
Thank you for the great work so far, could you please add the new scaling methods FSR, CAS and Nvidia image scaling to your results?

**Comment by Obegg** [comment]
Yes, please add them to your results.
I really want to know which user shader is best now that we have new ones.
They can be found here: https://github.com/mpv-player/mpv/wiki/User-Scripts#user-shaders

[FidelityFX CAS](https://gist.github.com/agyild/bbb4e58298b2f86aa24da3032a0d2ee6)
AMD FidelityFX Contrast Adaptive Sharpening (CAS) provides a mixed ability to sharpen and optionally scale an image. The algorithm adjusts the amount of sharpening per pixel to target an even level of sharpness across the image. Areas of the input image that are already sharp are sharpened less, while areas that lack detail are sharpened more. This allows for higher overall natural visual sharpness with fewer artifacts.

[FidelityFX FSR](https://gist.github.com/agyild/82219c545228d70c5604f865ce0b0ce5)
AMD FidelityFX Super Resolution is a spatial upscaler: it works by taking the current anti-aliased frame and upscaling it to display resolution without relying on other data such as frame history or motion vectors. At the heart of FSR is a cutting-edge algorithm that detects and recreates high-resolution edges from the source image. Those high-resolution edges are a critical element required for turning the current frame into a “super resolution” image. FSR provides consistent upscaling quality regardless of whether the frame is in movement, which can provide quality advantages compared to other types of upscalers.

[NVIDIA Image Scaling](https://gist.github.com/agyild/7e8951915b2bf24526a9343d951db214)
NVIDIA Image Scaling is a spatial scaling and sharpening algorithm. The scaling algorithm uses a 6-tap scaling filter combined with 4 directional scaling and adaptive sharpening filters, which creates nice smooth images and sharp edges. In addition, an adaptive-directional sharpening-only algorithm is available. The directional scaling and sharpening algorithm is named NVScaler while the adaptive-directional-sharpening-only algorithm is named NVSharpen.

**Comment by Artoriuz** [comment]
I'll think about adding these, but I don't expect them to compete with the actual CNNs...

**Comment by CrHasher** [comment]
> I'll think about adding these, but I don't expect them to compete with the actual CNNs...

Made my own tests and FSR is a bit lower PSNR than even the gpu-hq profile.

My PSNR calculations:
gpu-hq: 45.36485807077690
gpu-hq+FSR: 43.09941962786760

Strange enough I prefer FSR over gpu-hq, looks pretty sharp without a lot of ringing and aliasing.

**Comment by Jules-A** [comment]
The ported FSR is way too sharp, is it possible to set the sharpening to 1.0 instead of the default 0 for further tests or at the very least 0.2. I'm not sure if it's similar but that's what AMD use for the UE plugin's default with their scaling logic as 
```
0.0: sharpest
1.0: 1/2 as sharp
2.0: 1/4 as sharp
3.0: 1/8 as sharp
```
