### ISSUE TITLE
Any chance of testing more inbuilt chroma scalers?

### ISSUE THREAD

**Issue by Jules-A** [Artoriuz/artoriuz.github.io#16]
Particularly interested in Hamming, Kaiser and maybe Catmull_Rom (mainly since it more well known).

**Comment by Artoriuz** [comment]
Upscaling is upscaling, it doesn't really matter that you're resampling a chroma plane. I've already covered most if not all filters available in mpv: https://artoriuz.github.io/blog/imagemagick_resampling.html

**Comment by Jules-A** [comment]
It's not quite a simple as that, maybe it is for the automatic tools but subjectively they produce a different variance of artifacts and some types of artifacts aren't seen as much in chroma scaling than luma scaling.
