### ISSUE TITLE
Evaluate the SuperXBR filter?

### ISSUE THREAD

**Issue by Dwedit** [Artoriuz/artoriuz.github.io#5]
I just found your page about upscaling algorithms, and I wanted to mention Hylian's SuperXBR filter.
It is an edge-directed image scaling algorithm that runs in two phases, first to calculate between pixels diagonally, then to fill in the rest of the pixels.  There was a [discussion about adding it into MPV Player](https://github.com/mpv-player/mpv/issues/3226), but it was ultimately decided as Wontfix.

The shader code is available from [the libretro common shaders repository](https://github.com/libretro/common-shaders/tree/master/xbr/shaders/super-xbr), look for super-xbr-pass0.cg and super-xbr-pass1.cg.  There's also a version for GLSL and SLANG.  First, you run pass 0 on the original image, for an output image of the same size.  Then you run Pass 1 on two textures, the original texture, and the result of pass 0, for an output image double sized.

**Comment by deus0ww** [comment]
SuperXBR was available from @bjin but was removed. I wouldn't recommend it but you can dig it out of his repo here:
https://github.com/bjin/mpv-prescalers/tree/3e6b76087dc2b4d794ba7a0a5a3e7b7eb8f7f6f3

**Comment by Artoriuz** [comment]
SuperXBR performs worse than the alternatives (SSSR, Ravu-zoom).
