### ISSUE TITLE
Old Violet tables are not hosted anymore

### ISSUE THREAD

**Issue by brian6932** [Artoriuz/artoriuz.github.io#7]
![image](https://user-images.githubusercontent.com/18603393/120489229-7a02c280-c385-11eb-91de-cf645a5124f9.png)
https://artoriuz.github.io/blog/images/mpv_upscaling/tables/old/
![image](https://user-images.githubusercontent.com/18603393/120489504-ae767e80-c385-11eb-8821-0cd769f4131c.png)

**Comment by Artoriuz** [comment]
Hi Brian, the link was broken. It should be fine now, thanks.
